name: Actualizar Insignias de Credly

on:
  schedule:
    - cron: '0 2 * * *' # Se ejecuta automáticamente todos los días
  workflow_dispatch: # Permite ejecución manual rápida

permissions:
  contents: write # Permiso obligatorio para que GitHub pueda editar tu archivo README

jobs:
  update-badges:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Actualizar README con Credly
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: "kevin-daniel-yuvi-chamorro" # Tu usuario verificado
          NUMBER_LAST_BADGES: 0 # Muestra absolutamente todas tus insignias disponibles
